### ISSUE TITLE
Do you plan to have support for Windows and Mac OS? 

### ISSUE THREAD

**Issue by karol-brejna-i** [logikal-io/install-chrome#4]

**Comment by GergelyKalmar** [comment]
I did not really have plans for Windows/Mac OS because I mostly use Ubuntu runners, but I'm also not against it if anyone wants to add that functionality (as long as it doesn't increase complexity a lot). Alternatively, you might use https://github.com/browser-actions/setup-chrome which has better cross-platform support, although that action doesn't support pinning to a specific version yet, which is what I needed to get deterministic runs. It might be easier to add version specifications to that action than to add Window/Mac OS support to this action though.

**Comment by karol-brejna-i** [comment]
Actually, I tried the action you mentioned -- it didn't fit my needs. I googled your action and was able to use it straight away. And it is very to the point. Not bad as for code that was 6 hours old ;-) (at that time).
Thank you for the project. If I need to run my workflow against Windows sometime in the future, I'll probably propose a change (Windows support).
